### ISSUE TITLE
Property android/ios is not allowed in deploy.yaml

### ISSUE THREAD

**Issue by shahmirzali49** [andrewpmoore/simple_deploy#7]
<img width="754" alt="Screenshot 2024-11-24 at 13 24 21" src="https://github.com/user-attachments/assets/758725e6-ee4e-4deb-a0f4-0a500bd1bc40">

**Comment by shahmirzali49** [comment]
```
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  simple_deploy: ^0.25.0
```
