### ISSUE TITLE
Unable to upload to TestFlight

### ISSUE THREAD

**Issue by prolanzer** [andrewpmoore/simple_deploy#8]
The problem is the generated ipa is always named as `yourapp_app.ipa` even though no name is specified in the deploy.yaml

```yaml
common:
  versionStrategy: "none"

android:
  credentialsFile: "keys/android-credentials.json"
  packageName: "my.app"

ios:
  teamKeyId: "XXX"
  developerId: "xxxx"
```

The workaround is to use `generatedFileName: "yourapp_app.ipa"`. The project name is `yourapp_app` though.
